name: ml-tf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - astunparse=1.6.3=py_0
  - autopep8=1.4.4=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.12.8=h06a4308_0
  - cachetools=3.1.1=py_0
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - flake8=3.7.9=py37_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.3=py_0
  - glib=2.63.1=h3eb4bd4_1
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - intel-openmp=2020.1=217
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.0=py37_0
  - joblib=0.15.1=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_1
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1i=h27cfd23_0
  - pandas=1.0.3=py37h0573a6f_0
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_3
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.11.4=py37he6710b0_0
  - ptyprocess=0.6.0=py37_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.20=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=46.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - sqlite=3.31.1=h62c20be_1
  - tensorboard-plugin-wit=1.6.0=py_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - werkzeug=1.0.1=py_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.11.0
    - flatbuffers==1.12
    - grpcio==1.32.0
    - keras-preprocessing==1.1.2
    - numpy==1.19.4
    - opt-einsum==3.3.0
    - six==1.15.0
    - tensorboard==2.4.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - typing-extensions==3.7.4.3
    - wheel==0.36.2
prefix: /home/dlzou/anaconda3/envs/ml-tf
